name: Build All Platforms
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          mkdir -p server/database
          mkdir -p server/uploads
          npm install
          npm run build -- --win
      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/

  build-mac:
    runs-on: macos-12
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install dependencies
        run: |
          brew install gon
          npm install
          
      - name: Build app
        run: npm run build -- --mac
          
      - name: Notarize with retry
        env:
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
        run: |
          # 生成配置文件
          cat <<EOF > gon.json
          {
            "source": ["dist/mac/*.app"],
            "bundle_id": "com.example.quotation",
            "apple_id": {
              "username": "2441686096@qq.com",
              "password": "@env:AC_PASSWORD"
            },
            "notarize": {
              "timeout": 600,
              "retries": 3,
              "retry_wait": 60
            }
          }
          EOF
          
          # 带重试的公证
          for i in {1..3}; do
            gon gon.json && break || sleep 60
            echo "Notarization attempt $i failed, retrying..."
          done
          
          # 强制验证结果
          xcrun stapler validate dist/mac/*.app || true

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          mkdir -p www
          cp -R src/* www/ || true
          echo '{
          "appId": "com.example.quotation",
          "appName": "报价单系统",
          "webDir": "www"
          }' > capacitor.config.json
          npm install
          npx cap add android
          npx cap sync
          cd android && ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: android/app/build/outputs/apk/debug/