name: Build All Platforms
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          mkdir -p server/database
          mkdir -p server/uploads
          npm install
          npm run build -- --win
      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/

  build-mac:
    runs-on: macos-latest
    timeout-minutes: 45
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 安装 gon 的正确方式
      - name: Install gon (correct method)
        run: |
          brew tap mitchellh/gon
          brew install mitchellh/gon/gon

      # 构建步骤
      - name: Build App
        run: |
          mkdir -p www server/database server/uploads
          cp -R src/* www/ || true
          
          # 强制清理旧构建
          rm -rf dist/mac*
          
          npm ci
          npm run build -- --mac
          
          # 修复路径：重命名输出目录（适配electron-builder 24+）
          if [ -d "dist/mac-arm64" ]; then
            mv dist/mac-arm64 dist/mac
          fi
          
      # 公证步骤
      - name: Notarize App
        env:
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
        run: |
          # 1. 强制使用英文路径（关键修复）
          APP_PATH="$PWD/dist/mac/Quotation.app"
          [ -d "$PWD/dist/mac/报价单系统.app" ] && mv "$PWD/dist/mac/报价单系统.app" "$APP_PATH"
          
          # 2. 使用原生JSON生成（避免Python依赖）
          cat > gon.json <<EOF
          {
            "source": ["$APP_PATH"],
            "bundle_id": "com.tulan-913.quotation",
            "apple_id": {
              "username": "2441686096@qq.com",
              "password": "@env:AC_PASSWORD"
            },
            "notarize": {
              "timeout": 1200
            }
          }
          EOF

          # 4. 执行公证（带详细日志）
          gon -log-level=debug gon.json
          
          # 6. 钉扎公证票
          xcrun stapler staple "$APP_PATH"

      - uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: dist

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          mkdir -p www
          cp -R src/* www/ || true
          echo '{
          "appId": "com.example.quotation",
          "appName": "报价单系统",
          "webDir": "www"
          }' > capacitor.config.json
          npm install
          npx cap add android
          npx cap sync
          cd android && ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: android/app/build/outputs/apk/debug/