name: Build All Platforms
on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
         node-version: 20
      - run: |
          mkdir -p server/database
          mkdir -p server/uploads
          npm install
          npm run build -- --win
      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          mkdir -p www
          cp -R src/* www/ || xcopy /E /Y src\\* www\\ 
          npm install
          npm run build -- --mac
      - uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: dist/

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          mkdir -p www
          cp -R src/* www/ || true
          echo '{
          "appId": "com.example.quotation",
          "appName": "报价单系统",
          "webDir": "www"
          }' > capacitor.config.json
          npm install
          npx cap add android
          npx cap sync
          cd android && ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: android/app/build/outputs/apk/debug/


  build-ios:
    runs-on: macos-latest  # 必须使用 macOS（Xcode 依赖）
    steps:
      - uses: actions/checkout@v4  # 拉取代码

      - name: 设置 Node.js 环境
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 安装依赖
        run: |
          npm install
          npm install -g @capacitor/cli  # 全局安装 CLI（避免 npx 问题）

      - name: 构建前端（如果有）
        run: |
          if [ -f "package.json" ] && grep -q '"build"' package.json; then
            npm run build  # 执行前端构建（如 Vue/React 项目）
          fi

      - name: 准备 Capacitor 目录
        run: |
          rm -rf www || true
          mkdir -p www
          # 优先复制 dist/（构建后），其次 src/（源代码）
          if [ -d "dist" ]; then
            cp -R dist/* www/
          elif [ -d "src" ]; then
            cp -R src/* www/
          else
            echo "错误：找不到前端代码目录（dist 或 src）"
            exit 1
          fi

      - name: 初始化 Capacitor
        run: |
          if [ ! -f "capacitor.config.json" ]; then
            npx cap init "报价单系统" "com.example.quotation" --web-dir www
          fi
          npx cap add ios  # 添加 iOS 平台
          npx cap sync ios  # 同步依赖

      - name: 安装 iOS 依赖 (CocoaPods)
        run: |
          cd ios/App
          pod install --repo-update  # 自动更新仓库
          cd ../..

      - name: 构建 IPA
        run: |
          xcodebuild -workspace ios/App/App.xcworkspace \
                    -scheme App \
                    -configuration Release \
                    -archivePath build/App.xcarchive \
                    archive
          xcodebuild -exportArchive \
                    -archivePath build/App.xcarchive \
                    -exportOptionsPlist ios/App/exportOptions.plist \
                    -exportPath build/ipa

      - name: 上传 IPA 产物
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: ios/build/ipa