name: Build All Platforms
on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          mkdir -p server/database
          mkdir -p server/uploads
          npm install
          npm run build -- --win
      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/

  build-mac:
    runs-on: macos-13-ventura-xlarge
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Turbo Build & Notarize
        env:
          AC_PASSWORD: ${{ secrets.AC_PASSWORD }}
        run: |
          (
            mkdir -p www && cp -R src/* www/
            npm ci --no-audit
            npm run build -- --mac
          ) &
          (
            brew install --quiet --no-quarantine gon
          ) &
          wait
          
          echo '{
            "source": ["dist/mac/*.app"],
            "bundle_id": "com.example.quotation",
            "apple_id": {
              "username": "2441686096@qq.com",
              "password": "@env:AC_PASSWORD"
            },
            "notarize": {
              "timeout": 1200
              "skip_wait": true
            }
          }' > gon.json
          
          gon --fast gon.json
          
          xattr -cr dist/mac/*.app &
          spctl -a -t exec -vv dist/mac/*.app &

      - uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: dist/
          compression-level: 0

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          mkdir -p www
          cp -R src/* www/ || true
          echo '{
          "appId": "com.example.quotation",
          "appName": "报价单系统",
          "webDir": "www"
          }' > capacitor.config.json
          npm install
          npx cap add android
          npx cap sync
          cd android && ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: android/app/build/outputs/apk/debug/