name: Build All Platforms
on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          mkdir -p server/database
          mkdir -p server/uploads
          npm install
          npm run build -- --win
      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: dist/

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          mkdir -p www
          cp -R src/* www/ || xcopy /E /Y src\\* www\\ 
          npm install
          npm run build -- --mac
      - uses: actions/upload-artifact@v4
        with:
          name: mac-build
          path: dist/

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          mkdir -p www
          cp -R src/* www/ || true
          echo '{
          "appId": "com.example.quotation",
          "appName": "报价单系统",
          "webDir": "www"
          }' > capacitor.config.json
          npm install
          npx cap add android
          npx cap sync
          cd android && ./gradlew assembleDebug
      - uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: android/app/build/outputs/apk/debug/


  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      # 1. 安全的清理旧文件（忽略不存在的目录）
      - name: Clean Workspace
        run: |
          [ -d "ios" ] && rm ios || true
          [ -d "www" ] && rm www || true
          [ -d "node_modules" ] && rm node_modules || true
      
      # 2. 安装依赖
      - name: Install Dependencies
        run: |
          npm install
          mkdir -p www
          cp -R src/* www/ || true
      
      # 3. 初始化iOS平台
      - name: Setup iOS Platform
        run: |
          npx cap add ios
          cd ios/App
          
          # 确保Podfile存在
          if [ ! -f "Podfile" ]; then
            pod init
            echo "platform :ios, '13.0'" > Podfile
            echo "target 'App' do" >> Podfile
            echo "  use_frameworks!" >> Podfile
            echo "  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'" >> Podfile
            echo "  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'" >> Podfile
            echo "end" >> Podfile
          fi
          
          pod install
          cd ../..
      
      # 4. 构建IPA
      - name: Build IPA
        run: |
          cd ios
          xcodebuild -workspace App/App.xcworkspace \
                    -scheme App \
                    -configuration Release \
                    -archivePath build/App.xcarchive \
                    archive
          
          xcodebuild -exportArchive \
                    -archivePath build/App.xcarchive \
                    -exportOptionsPlist App/exportOptions.plist \
                    -exportPath build/ipa
      
      # 5. 上传产物
      - uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: ios/build/ipa
      